apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: b2-radarr-config
  namespace: media
spec:
  sourcePVC: radarr-config
  trigger:
    schedule: 11 0 * * 0
  restic:
    repository: b2-radarr-config-restic

    copyMethod: Snapshot
    volumeSnapshotClassName: truenas-ssd-iscsi
    storageClassName: truenas-ssd-iscsi

    pruneIntervalDays: 10
    cacheCapacity: 5Gi
    retain:
      daily: 7
      weekly: 4
      monthly: 6
      within: 3d

    moverSecurityContext:
      runAsUser: ${FILESHARE_USER_ID}
      runAsGroup: ${FILESHARE_GROUP_ID}
      fsGroup: ${FILESHARE_GROUP_ID}
