apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piped
resources:
 - helmrelease-piped.yaml
 - kustomization-piped-config.yaml
 - sealed-secret-piped-postgres-credentials.yaml
