apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piped-config
  namespace: piped
  
spec:
  interval: 5m
  wait: true
  prune: true
  path: ./cluster/piped/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m # if not set, this defaults to interval duration, which is 1h
  postBuild:
    substituteFrom:
      - kind: Secret
        name: piped-postgres-credentials
    substitute:
      CLUSTER_DOMAIN: ${CLUSTER_DOMAIN}
